### ISSUE TITLE
Tags sind nicht konfigurierbar, wenn das Ziel ein übersetzbares MM ist

### ISSUE THREAD

**Issue by andreasisaak** [MetaModels/attribute_translatedtags#1]
Szenario: 
MM-Functions sind MM mit translated-text als Funktionsnamen, weitere Felder sind nicht definiert.
MM-Products soll als (translated)Tags die MM-Functions einbinden - leider ist das im BE nicht sinnvoll möglich, da die translated-Attribute in der tabelle mm_functions nicht vorhanden sind und man schlecht die Tabelle tl_metamodel_translatedtext auswählen kann.

_--- Originally created by davidmaack_

**Comment by zonky2** [comment]
Die Arbeitsweise ist inzwischen anders - ein MM mit übersetzten Texten wird als unübersetztes Attribut [tags] eingebunden - die Übersetzung läuft inzwischen automatisch...

@discordier m.E. kann das Ticket zu - oder?

**Comment by discordier** [comment]
aye
