### ISSUE TITLE
Error if column name "condition"

### ISSUE THREAD

**Issue by zonky2** [MetaModels/attribute_translatedtags#16]
Error 1064 if column name "condition" with MariaDB

![Zwischenablage02](https://user-images.githubusercontent.com/1045318/115016784-d7b27c80-9eb5-11eb-8bc5-ee415a2e9bd0.png)

**Comment by discordier** [comment]
Need stack trace. From the look of the query, I'd guess this is from a "select" attribute.

**Comment by zonky2** [comment]
In MM 2.2 all column anmes save
