### ISSUE TITLE
translated_tags not working

### ISSUE THREAD

**Issue by JLBA** [MetaModels/attribute_translatedtags#19]
## Checklist before I submit this issue report

I confirm that:
- [x ] I have tested this with the latest version available
- [ x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x ] I have checked the Contao community forums for references https://community.contao.org/
- [ x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/attribute_translatedtags/issues?q=is%3Aissue

## My environment is: 

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |    7.4      |                                  |
| Contao version:                     |   4.9  |                                  |
| MetaModels version:                 | 2.1         |                                  |
| Installation via composer           | yes |                                  |
| Installed MetaModels packages       |   bundle_all, translated_tags,      |                                  |

## Issue description

(Describe the problem you are having)

## Steps to reproduce
1. mm_equipe to list the team members (with translations fr, en, es)
translated_tags 'zonegeo' linked to mm_pays
2. mm_pays to list the countries of intervention (with translations fr, en, es for countries names)
- translated_text 'nom_pays_trad'
- alias : pays_ref_alias

## Describe the behaviour of the application
I the input mask, I can't select tags with this error :  
Error: An exception occurred while executing 'SELECT COUNT(source.id) AS mm_count, source.id, source.pays_ref_alias FROM mm_pays_ref source GROUP BY source.id ORDER BY nom_pays_trad ASC': SQLSTATE[42S22]: Column not found: 1054 Unknown column 'nom_pays_trad' in 'order clause'

## Describe the expected behaviour of the application
For each member, I would like to select one or many countries of interventions. I want these countries names to be displayed with the right corresponding country name (fr: France, en : France, es: Francia)

## Screenshots

![image](https://user-images.githubusercontent.com/2730432/187895110-3280444f-7813-4e5f-9e09-23b9cab5a5a1.png)

Thanks for help.

**Comment by zonky2** [comment]
translated_tags is intended for tables that do not come from MetaModels and where there is a separate row for each language entry.

the "normal" tags attribute can automatically handle multiple languages if the relation goes to an MM table

**Comment by JLBA** [comment]
ok. So I understand why it asks for language row. 
My confuse. Thanks for the answer.
