### ISSUE TITLE
Implement widgetToValue to include tag_value_sorting.

### ISSUE THREAD

**Issue by discordier** [MetaModels/attribute_translatedtags#5]
The commit https://github.com/MetaModels/attribute_tags/commit/ce0023369d1b1116aef1f9139d6bf9fe21665be0 caused issue #4.

To solve the initial reason for above mentioned commit, we need to implement the method widgetToValue() in translated tags, so the configured sorting column will get used (instead of using the hardcoded column name "sorting" as in the reverted commit which reflected the real column name by accident).

**Comment by zonky2** [comment]
@discordier is this still up to date? we can select a sorting column in the meantime!
