### ISSUE TITLE
Change to using filters in MetaModel data source

### ISSUE THREAD

**Issue by cboelter** [MetaModels/attribute_translatedtags#9]

**Comment by discordier** [comment]
Means? ;)

**Comment by cboelter** [comment]
That there is the old Where-Field if I choose a MetaModel as DataSource, but in the nontranlsated we have the filterselection.

**Comment by discordier** [comment]
You mean the other way around?
MetaModel data source has an filter but plain table has the where-field I suppose?
If so, which commits are you referring to?

**Comment by cboelter** [comment]
Yes in the nontranslated attribute the MetaModels data source has an filter, but in the translated we do have there where-field in both data source. I have changed the title because I think there must be more rework. My Commits in the Attribute-Tags are only fixes for the work of Stefan Heimes.

**Comment by xantippe** [comment]
@cboelter noch aktuell?

**Comment by zonky2** [comment]
hmm ... nobody have a idea of the reason of this ticket... bay be, at the future...
